from ._Error import Error


class LoopGiaImpostatoError(Error):
    pass
